# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9593fd28b7d7a3217d87239dec100ada35f34b45c0faac1a7c7acf5344e889ba76cb9551ea019b84bd33019a00cedab4985ff60dab9184661e08372d01052afd

test:
  secret_key_base: dc8d423dfba40f4864c79973f2c38fb7a9e731a397fcaa0fae14d6affbd0680471886c5747014f228d6044ded5aa05e4386a5f3da6488ecc9b14b3ac3fa094a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
